### ISSUE TITLE
Image source with v-bind

### ISSUE THREAD

**Issue by bransfieldjack** [laurenashpole/vue-inner-image-zoom#1]
Excellent component! Wondering if there is support for v-bind?

For example,

~~~
<v-col cols="12" md="5">
          <inner-image-zoom :src="item['image'][0]['url']"/>
</v-col>
~~~

**Comment by laurenashpole** [comment]
Hey @bransfieldjack, sorry I'm slow seeing this. There isn't currently support for v-bind but if it's something that would be useful I could definitely take a look.

**Comment by laurenashpole** [comment]
This should finally work and was tested in the demos in v1.1.0.
