### ISSUE TITLE
[Bug] Image disappears on iPad 4th gen. 

### ISSUE THREAD

**Issue by cpreston321** [laurenashpole/vue-inner-image-zoom#2]
### Component Bug 
I encountered this bug when testing it on different devices. If you just pull up your site and click zoom on iPad Device then click X it will disappear and it won't come back till you refresh page. @laurenashpole

**Comment by laurenashpole** [comment]
@cpreston321 Thanks for the heads up, I'll try to take a look at that this week.

**Comment by cpreston321** [comment]
> @cpreston321 Thanks for the heads up, I'll try to take a look at that this week.

Seems at diving a little deeper that when I was debugging on the IPAD it seem to have the class that makes it invisible on the image ```.iiz__img--invisible``` . I will play around with it more tomorrow to debug the actually code.

**Comment by laurenashpole** [comment]
@cpreston321 Sorry that took a bit, I was a little too optimistic about how much time I would have over the holidays.

Just released a fix (v1.0.1). It turns out that was happening any time the zoomed image wasn't displayed in fullscreen on a touch device so I'm glad you noticed it!
