### ISSUE TITLE
Unable to use with Nuxt.js

### ISSUE THREAD

**Issue by dzcpy** [laurenashpole/vue-inner-image-zoom#45]
![image](https://user-images.githubusercontent.com/203980/158206909-b1f194e4-98c5-4486-acb6-1e074d4666bb.png)
```vue
<template>
  <div id="app">
    <h1>vue-inner-image-zoom Demo</h1>
    <div style="margin-bottom: 30px">
      <h2>Zoom on Hover Example</h2>
      <client-only>
        <inner-image-zoom
          src="@/assets/images/1.png"
          zoom-src="@/assets/images/2.png"
          zoom-type="hover"
          :fullscreen-on-mobile="true"
          :zoom-scale="0.9"
          :zoom-preload="true"
        />
      </client-only>
    </div>
  </div>
</template>

<script>
import InnerImageZoom from 'vue-inner-image-zoom'
export default {
  name: 'App',
  components: {
    InnerImageZoom,
  },
}
</script>

```

**Comment by gigamarr** [comment]
Have you resolved or found any alternative?

**Comment by madiyetov** [comment]
Hey @gigamarr @dzcpy, maybe you are trying to use `2.0.0` version of this package with `Vue 2` (it's for `Vue 3`). If that's your case, try v1.1.1. It worked for me.

**Comment by dosstx** [comment]
Just tested....works fine in Nuxt3

**Comment by laurenashpole** [comment]
Glad this worked out. Thanks @madiyetov and @dosstx for jumping in to help!

**Comment by toddpadwick** [comment]
Hi everyone, can any of you tell me how they've managed to set this up in Nuxt 3? I have the following but it's not registering the component in my templates:

```
// ~/plugins/inner-image-zoom.js

import InnerImageZoom from 'vue-inner-image-zoom'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(InnerImageZoom)
})
```

Also does it support SSR? as this would be crucial for SEO so the images can be indexed.

**Comment by dosstx** [comment]
I had it working in Nuxt3 way back when they were on RC 1. Now that Nuxt3 is stable, I am going to look at putting it back in. I'll report back.

If you can't wait until then, I believe you have to mount the zoom plugin in the `onMounted` hook or add the `.client` extension to the plugin file name so the zoom plugin only loads after SSR. 

With that said, why does the the plugin need to be SSR? Just serve a regular image for SSR and then fall back to the zoom plugin for SPA mode.

**Comment by toddpadwick** [comment]
Thanks @dosstx , that would be fantastic. The reason it would be best to support SSR is so that it still renders the image tag with indexable alt tags, and image src. 
As you say, I could do something like this which I presume is what you meant:
if (process.client) {
< InnerImageZoom src="xxxxx">
else {
<img src="xxxx">
}

but that feels really clunky. also means the image will have to render twice and may result in a flicker.
